In [ ]:
%matplotlib inline

텐서(Tensor)
==========================================================================

텐서(tensor)는 배열(array)이나 행렬(matrix)과 매우 유사한 특수한 자료구조이다.
PyTorch에서는 텐서를 사용하여 모델의 **입력(input)**과 **출력(output)**, 그리고 모델의 **매개변수**들을 저장한다.

텐서는 GPU나 다른 하드웨어 가속기에서 실행할 수 있다는 점만 제외하면 `NumPy`의 `ndarray`와 유사하다.
실제로 텐서와 NumPy 배열(array)은 종종 동일한 내부 메모리를 공유할 수 있어 데이터를 복사할 필요가 없기도 하다(참고: [Bridge with NumPy](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#bridge-to-np-label)).

텐서는 또한 자동 미분(automatic differentiation)에 최적화되어 있다. 자동 미분에 대해서는 나중에 따로 다룬다.



In [ ]:
import torch
import numpy as np

## 텐서(tensor) 초기화

### 데이터로부터 직접 생성하기

데이터로부터 직접 텐서를 생성할 수 있다. 데이터의 자료형(data type)은 자동으로 유추한다.

In [ ]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


### NumPy 배열로부터 생성하기

텐서는 NumPy 배열로 생성할 수 있다. 그 반대도 가능하다.



In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])


### 다른 텐서로부터 생성하기



명시적으로 재정의(override)하지 않는다면, 인자로 주어진 텐서의 속성(모양(shape), 자료형(datatype))을 유지한다.



In [ ]:
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지합니다.
print(f"Ones Tensor: \n {x_ones} \n")

x_zeros = torch.zeros_like(x_data) # x_data의 속성을 유지합니다.
print(f"Ones Tensor: \n {x_zeros} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어씁니다.
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Ones Tensor: 
 tensor([[0, 0],
        [0, 0]]) 

Random Tensor: 
 tensor([[0.5125, 0.1754],
        [0.1239, 0.9569]]) 



### 무작위(random) 또는 상수(constant) 값을 사용하기

``shape`` 은 텐서의 차원(dimension)을 나타내는 튜플(tuple)로, 아래 함수들에서는 출력 텐서의 차원을 결정한다.



In [ ]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5982, 0.4889, 0.5334],
        [0.9571, 0.7490, 0.7135]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


--------------

## 텐서의 속성(Attribute)


텐서의 속성은 텐서의 모양(shape), 자료형(datatype) 및 어느 장치에 저장되는지를 나타낸다.



In [ ]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
torch.Size([3, 4])


--------------

## 텐서 연산(Operation)

전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수,
임의 샘플링(random sampling) 등 다양한 텐서 연산들을
[여기](<https://pytorch.org/docs/stable/torch.html>)에서 확인할 수 있다.

각 연산들은 (일반적으로 CPU보다 빠른) GPU에서 실행할 수 있다. Colab을 사용한다면, Edit > Notebook Settings 에서 GPU를 할당할 수 있다.

기본적으로 텐서는 CPU에 생성된다. ``.to`` 메소드를 사용하면 (GPU의 가용성(availability)을 확인한 뒤) GPU로 텐서를 명시적으로 이동할 수 있다. 장치들 간에 큰 텐서들을 복사하는 것은 시간과 메모리 측면에서 비용이 많이든다는 것을 기억하라!

In [ ]:
# GPU가 존재하면 텐서를 이동합니다
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

목록에서 몇몇 연산들을 시도해보라.
NumPy API에 익숙하다면 Tensor API를 사용하는 것은 식은 쉽다는 것을 알게 될 것이다.

**NumPy 방식의 인덱싱과 슬라이싱:**



In [ ]:
# tensor = torch.ones(4, 4)
tensor = torch.tensor([[1,2,3,4],
                       [5,6,7,8],
                       [9,10,11,12],
                       [13,14,15,16]
                       ])
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1, 2, 3, 4])
First column: tensor([ 1,  5,  9, 13])
Last column: tensor([ 4,  8, 12, 16])
tensor([[ 1,  0,  3,  4],
        [ 5,  0,  7,  8],
        [ 9,  0, 11, 12],
        [13,  0, 15, 16]])


**텐서 합치기:** 

``torch.cat``을 사용하여 주어진 차원에 따라 일련의 텐서를 연결할 수 있다.
``torch.cat``과 미묘하게 다른 또 다른 텐서 결합 연산인
[`torch.stack`](<https://pytorch.org/docs/stable/generated/torch.stack.html>)도 참고하라.



In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


**산술 연산(Arithmetic operations)**



In [ ]:
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산합니다. y1, y2, y3은 모두 같은 값을 갖습니다.
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# 요소별 곱(element-wise product)을 계산합니다. z1, z2, z3는 모두 같은 값을 갖습니다.
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

**단일-요소(single-element) 텐서:** 

단일 스칼라 값을 저장하는 텐서의 경우, ``item()``을 사용하여 숫자 값으로 변환할 수 있다:



In [ ]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


**바꿔치기(in-place) 연산:**

연산 결과를 피연산자(operand)에 저장하는 연산을 바꿔치기 연산이라고 부르며, ``_`` 접미사를 갖는다.
예를 들어: ``x.copy_(y)`` 나 ``x.t_()`` 는 ``x`` 를 변경한다.



In [ ]:
print(f"{tensor} \n")
tensor.add_(5) # _ means mutating operation
print(tensor)

**Note:** 바꿔치기 연산은 메모리를 일부 절약하지만, 기록(history)이 즉시 삭제되어 도함수(derivative) 계산에 문제가 발생할 수 있다. 따라서, 사용을 권장하지 않는다.



--------------




## NumPy 변환(Bridge)

CPU 상의 텐서와 NumPy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경된다.



**텐서를 NumPy 배열로 변환하기**


In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


텐서의 변경 사항이 NumPy 배열에 반영된다.



In [ ]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


**NumPy 배열을 텐서로 변환하기**

In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

NumPy 배열의 변경 사항이 텐서에 반영된다.



In [ ]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
